fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.1.0'
    wget:
      repo: 'git://github.com/maestrodev/puppet-wget.git'
      ref: 'v1.5.6'
  symlinks:
    teecli: "#{source_dir}"
