HOSTS:
 centos-64-x64: 
  roles: 
   - master
  platform: el-6-x86_64
  image: devopsil/puppet:3.5.1
  hypervisor : docker
  docker_image_commands: 
   - 'yum -y install tar'
CONFIG:
 log_level: verbose